-- Schema for PlantCare App

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    phone TEXT,
    bio TEXT,
    location TEXT,
    avatar_url TEXT,
    join_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    stats JSONB DEFAULT '{"totalPlants": 0, "wateringSessions": 0, "successRate": 100}'::jsonb
);

-- RLS for Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Trigger to create profile on sign up
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 2. Plants Table
CREATE TABLE IF NOT EXISTS public.plants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    img_url TEXT,
    bio TEXT,
    location TEXT,
    status TEXT DEFAULT 'healthy',
    last_watered TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS for Plants
ALTER TABLE public.plants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own plants" ON public.plants FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own plants" ON public.plants FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own plants" ON public.plants FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own plants" ON public.plants FOR DELETE USING (auth.uid() = user_id);


-- 3. Plant Metrics (Analytics) Table
CREATE TABLE IF NOT EXISTS public.plant_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT REFERENCES public.plants(id) ON DELETE CASCADE NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    air_humidity_pct NUMERIC,
    temperature_c NUMERIC,
    soil_moisture_pct NUMERIC,
    light_level NUMERIC,
    device_id TEXT
);

-- RLS for Plant Metrics
ALTER TABLE public.plant_metrics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view metrics for their plants" ON public.plant_metrics 
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.plants 
            WHERE plants.id = plant_metrics.plant_id AND plants.user_id = auth.uid()
        )
    );
CREATE POLICY "Users can insert metrics for their plants" ON public.plant_metrics 
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.plants 
            WHERE plants.id = plant_metrics.plant_id AND plants.user_id = auth.uid()
        )
    );

-- 4. Watering Logs Table
CREATE TABLE IF NOT EXISTS public.watering_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT REFERENCES public.plants(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    watered_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS for Watering Logs
ALTER TABLE public.watering_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their watering logs" ON public.watering_logs 
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their watering logs" ON public.watering_logs 
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their watering logs" ON public.watering_logs 
    FOR DELETE USING (auth.uid() = user_id);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_watering_logs_plant_id ON public.watering_logs(plant_id);
CREATE INDEX IF NOT EXISTS idx_watering_logs_user_id ON public.watering_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_watering_logs_watered_at ON public.watering_logs(watered_at);
CREATE INDEX IF NOT EXISTS idx_plant_metrics_plant_id ON public.plant_metrics(plant_id);
CREATE INDEX IF NOT EXISTS idx_plant_metrics_timestamp ON public.plant_metrics(timestamp);

-- ============================================================
-- Experiment-Driven Development (Capítulo VIII) — Soporte EC-01 / EC-02
-- ============================================================

-- Columna para el webhook de Discord del usuario (US-041 / EC-01)
ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS discord_webhook_url TEXT;

-- 6. Premium Leads Table (US-042 / EC-02)
-- Registra el interés de un usuario que confirma la suscripción simulada.
CREATE TABLE IF NOT EXISTS public.premium_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    plan_id TEXT NOT NULL,
    source_feature TEXT,           -- 'premium_health' | 'premium_history'
    simulated BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.premium_leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their premium leads" ON public.premium_leads
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their premium leads" ON public.premium_leads
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_premium_leads_user_id ON public.premium_leads(user_id);

-- 7. Feature Interaction Logs Table (Tracking Plan 8.2.8)
-- Tabla de auditoría para eventos de interacción (select_promotion, view_promotion,
-- purchase_simulation, click_alert_link). Se escribe por lotes (batching) desde el frontend.
CREATE TABLE IF NOT EXISTS public.feature_interaction_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    event_name TEXT NOT NULL,      -- select_promotion | view_promotion | purchase_simulation | click_alert_link
    promotion_id TEXT,
    promotion_name TEXT,
    location TEXT,
    metadata JSONB,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.feature_interaction_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their interaction logs" ON public.feature_interaction_logs
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their interaction logs" ON public.feature_interaction_logs
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_feature_logs_user_id ON public.feature_interaction_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_feature_logs_event ON public.feature_interaction_logs(event_name);


-- 8. User Achievements Table (Gamificación · Hipótesis 5 — Insignia "Cuidador Experto")
-- Persiste el momento de desbloqueo de cada logro para mostrar la fecha real y
-- anclar el baseline de medición pre/post del experimento.
CREATE TABLE IF NOT EXISTS public.user_achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    achievement_id TEXT NOT NULL,
    unlocked_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (user_id, achievement_id)
);

ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their achievements" ON public.user_achievements
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their achievements" ON public.user_achievements
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_user_achievements_user_id ON public.user_achievements(user_id);


-- 5. Storage Bucket for Avatars (Optional, if using Supabase Storage)
-- insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true);


