-- Schema for PlantCare App

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    phone TEXT,
    bio TEXT,
    location TEXT,
    avatar_url TEXT,
    join_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    stats JSONB DEFAULT '{"totalPlants": 0, "wateringSessions": 0, "successRate": 100}'::jsonb
);

-- RLS for Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Trigger to create profile on sign up
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 2. Plants Table
CREATE TABLE IF NOT EXISTS public.plants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    img_url TEXT,
    bio TEXT,
    location TEXT,
    status TEXT DEFAULT 'healthy',
    last_watered TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS for Plants
ALTER TABLE public.plants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own plants" ON public.plants FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own plants" ON public.plants FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own plants" ON public.plants FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own plants" ON public.plants FOR DELETE USING (auth.uid() = user_id);


-- 3. Plant Metrics (Analytics) Table
CREATE TABLE IF NOT EXISTS public.plant_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT REFERENCES public.plants(id) ON DELETE CASCADE NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    air_humidity_pct NUMERIC,
    temperature_c NUMERIC,
    soil_moisture_pct NUMERIC,
    light_level NUMERIC,
    device_id TEXT
);

-- RLS for Plant Metrics
ALTER TABLE public.plant_metrics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view metrics for their plants" ON public.plant_metrics 
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.plants 
            WHERE plants.id = plant_metrics.plant_id AND plants.user_id = auth.uid()
        )
    );
CREATE POLICY "Users can insert metrics for their plants" ON public.plant_metrics 
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.plants 
            WHERE plants.id = plant_metrics.plant_id AND plants.user_id = auth.uid()
        )
    );

-- 4. Watering Logs Table
CREATE TABLE IF NOT EXISTS public.watering_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id BIGINT REFERENCES public.plants(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    watered_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS for Watering Logs
ALTER TABLE public.watering_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their watering logs" ON public.watering_logs 
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their watering logs" ON public.watering_logs 
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their watering logs" ON public.watering_logs 
    FOR DELETE USING (auth.uid() = user_id);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_watering_logs_plant_id ON public.watering_logs(plant_id);
CREATE INDEX IF NOT EXISTS idx_watering_logs_user_id ON public.watering_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_watering_logs_watered_at ON public.watering_logs(watered_at);
CREATE INDEX IF NOT EXISTS idx_plant_metrics_plant_id ON public.plant_metrics(plant_id);
CREATE INDEX IF NOT EXISTS idx_plant_metrics_timestamp ON public.plant_metrics(timestamp);

-- 5. Storage Bucket for Avatars (Optional, if using Supabase Storage)
-- insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true);


